# Generated by Django 4.2.2 on 2023-09-01 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppGestion', '0003_rename_producto_no_producto_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='id',
            new_name='prod_id',
        ),
    ]
