# Generated by Django 4.2.2 on 2023-09-01 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppGestion', '0004_rename_id_producto_prod_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='prod_id',
            new_name='id',
        ),
    ]
